name: web-deploy

on:
  push:
    branches:
      - 127-aws-deploy
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - run: ls
      - run: cat package.json
      
      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:web # will run `yarn build:web` command
 
      - name: Test project
        uses: borales/actions-yarn@v4
        with:
          cmd: test:web # will run `yarn test:web` command
          
      #- name: Upload production-ready build files
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: production-files
      #    path: ./dist
